export function numberedSyllableToTonemark(text: string): string {
    return text
        .replace(/v(.*?)1/g, 'ǖ$1')
        .replace(/v(.*?)2/g, 'ǘ$1')
        .replace(/v(.*?)3/g, 'ǚ$1')
        .replace(/v(.*?)4/g, 'ǜ$1')
        .replace(/a(.*?)1/g, 'ā$1')
        .replace(/a(.*?)2/g, 'á$1')
        .replace(/a(.*?)3/g, 'ǎ$1')
        .replace(/a(.*?)4/g, 'à$1')
        .replace(/e(.*?)1/g, 'ē$1')
        .replace(/e(.*?)2/g, 'é$1')
        .replace(/e(.*?)3/g, 'ě$1')
        .replace(/e(.*?)4/g, 'è$1')
        .replace(/i(.*?)1/g, 'ī$1')
        .replace(/i(.*?)2/g, 'í$1')
        .replace(/i(.*?)3/g, 'ǐ$1')
        .replace(/i(.*?)4/g, 'ì$1')
        .replace(/o(.*?)1/g, 'ō$1')
        .replace(/o(.*?)2/g, 'ó$1')
        .replace(/o(.*?)3/g, 'ǒ$1')
        .replace(/o(.*?)4/g, 'ò$1')
        .replace(/u(.*?)1/g, 'ū$1')
        .replace(/u(.*?)2/g, 'ú$1')
        .replace(/u(.*?)3/g, 'ǔ$1')
        .replace(/u(.*?)4/g, 'ù$1')
        .replace(/5/g, '')
}
